### ISSUE TITLE
和网易邮箱大师的兼容问题

### ISSUE THREAD

**Issue by allenzt** [rime/weasel#222]
因为issue #185 已经被closed， 所以把issue作者 @bingo1021 提到的问题另外开一个issue， 详情如下：
https://github.com/rime/weasel/issues/185#issuecomment-384508174

小狼毫：0.11.1
win OS version： 1709 OS build 16299.371
网易邮箱大师： v4.4.2.1006

**Comment by nameoverflow** [comment]
现在似乎已经解决这个问题了，不确定是在哪个 commit 解决的，也可能是邮箱大师更新解决的。
现在的行为和微软拼音是一致的。

**Comment by bingo1021** [comment]
我测试了，仍然存在这个问题啊。

网易邮箱大量、小狼毫均为最新版本，Windows10




            
            
                
                    
                            
                                
                            
                            
                                bingo
                            
                    
                        
                            
                                    邮箱：bingo2c@gmail.com
                            
                        
                
            
        


在2018年09月04日 17:45，nameoverflow 写道： Closed #222.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/rime/weasel","title":"rime/weasel","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/rime/weasel"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #222."}],"action":{"name":"View Issue","url":"https://github.com/rime/weasel/issues/222#event-1824822031"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/rime/weasel/issues/222#event-1824822031",
"url": "https://github.com/rime/weasel/issues/222#event-1824822031",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [rime/weasel] 和网易邮箱大师的兼容问题 (#222)",
"sections": [
{
"text": "",
"activityTitle": "**nameoverflow**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@nameoverflow",
"facts": [

]
}
],
"potentialAction": [
{
"targets": [
{
"os": "default",
"uri": "https://github.com/rime/weasel/issues/222#event-1824822031"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 330265783\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by bingo1021** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            https://rime.im/首页下载的
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                bingo
                            
                    
                        
                            
                                    bingo2c@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2018年9月4日 19:23，nameoverflow<notifications@github.com> 写道： 


「最新版」指的是 https://github.com/rime/weasel/tree/0.11.1 还是 https://github.com/rime/weasel/tree/master ？

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by nameoverflow** [comment]
Github 不支持邮件 CSS，请不要用带样式的邮件模版回复 issue。
rime.im 并没有同步开发进度，请等待正式版或者下载 CI 版。

**Comment by bingo1021** [comment]
好的。谢谢




            
            
                
                    
                            
                                
                            
                            
                                bingo
                            
                    
                        
                            
                                    邮箱：bingo2c@gmail.com
                            
                        
                
            
        


在2018年09月04日 20:39，nameoverflow 写道： Github 不支持邮件 CSS，请不要用带样式的邮件模版回复 issue。
rime.im 并没有同步开发进度，请等待正式版或者下载 CI 版。

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/rime/weasel","title":"rime/weasel","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/rime/weasel"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nameoverflow in #222: Github 不支持邮件 CSS，请不要用带样式的邮件模版回复 issue。\r\nrime.im 并没有同步开发进度，请等待正式版或者下载 CI 版。"}],"action":{"name":"View Issue","url":"https://github.com/rime/weasel/issues/222#issuecomment-418351665"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/rime/weasel/issues/222#issuecomment-418351665",
"url": "https://github.com/rime/weasel/issues/222#issuecomment-418351665",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [rime/weasel] 和网易邮箱大师的兼容问题 (#222)",
"sections": [
{
"text": "",
"activityTitle": "**nameoverflow**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@nameoverflow",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"rime/weasel\",\n\"issueId\": 222,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/rime/weasel/issues/222#issuecomment-418351665"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 330265783\n}"
}
],
"themeColor": "26292E"
}
]
