### ISSUE TITLE
how to configuration “set DEV_PATH=\opt\cmake-win32\bin” while compile weasel in env file？？

### ISSUE THREAD

**Issue by llf10811020205** [rime/weasel#27]
when i compile weasel as this meathod “build.bat all” some error  appeared like ：
无法打开包括文件:"boost/algorithm/string.hpp":No such file or directory [F:\weasel-develop\weaselIPC\WeaselIPC.vcxproj]？？？

**Comment by Prcuvu** [comment]
Did you set `BOOST_ROOT` in `env.bat` before executing `build.bat all`?

**Comment by llf10811020205** [comment]
I'm sure I set it ,but  i don't know hiow to set “DEV_PATH=\opt\cmake-win32\bin” ???

**Comment by Prcuvu** [comment]
`\opt\cmake-win32\bin` is a hint, telling you to set `DEV_PATH` to the directory where CMake binary is located, usually `C:\Program Files (x86)\CMake\bin`.

**Comment by llf10811020205** [comment]
Thank you very much ,I think i got it and After set env as you said,also appeared 无法打开包括文件:"boost/algorithm/string.hpp":No such file or directory [F:\weasel-develop\weaselIPC\WeaselIPC.vcxproj] This is a compile error ...

**Comment by lotem** [comment]
I've written a batch script to auto-detect tools install path for librime. I think the script can be ported to weasel with a few modifications so that manually creating env.bat can be avoided in most cases.
https://github.com/rime/librime/blob/develop/shell.bat

@llf10811020205 set a correct BOOST_HOME variable in weasel.props may fix the error.

**Comment by llf10811020205** [comment]
@Prcuvu @lotem , nothing could I say but thinks
