### ISSUE TITLE
编译weasel时，build.bat中的bash命令会优先触发Win10中的linux子系统

### ISSUE THREAD

**Issue by cjwdoing** [rime/weasel#287]
如题，Win10编译时，会触发标题中所述的问题。我是个新手来着，不知道需要怎么处理。以及，不知道build.bat中的bash应该是对应（git？cmake？或者其他）哪个工具中的命令？

**Comment by lotem** [comment]
原作的開發環境是調用 Git for Windows 捆綁的 bash。
不太瞭解 Win10 的 Linux 子系统，總之內含一套類似的 shell 工具集。
用起來有問題嘛？

**Comment by cjwdoing** [comment]
@lotem 是的，触发问题了。

事实上，新版的git中的bash似乎改名叫做git-bash.exe了。于是build.bat中从bash开始后面的命令都不会正确的。

此外，编译中也会提示boost下面引用不到windows.h头文件来着。估计是由于boost版本变化导致的。

如果可能的话，希望您能在编译说明中备注一下，您目前可以正常使用的是哪个版本的cmake、git和boost，这样想字性编译的人按照版本要求去找的话，可能会更容易成功:-)

（我在Win平台上编译weasel时已经遇到无数编译错误了，最后发现，果然还是Mac平台上的squireel比较容易编译，尽管编译说明中也有一处瑕疵，即xcode不能只安装命令行工具链，而是需要安装完整版，但这一点网上已经有人指出，因此按此说明一次就成功了~）

**Comment by lotem** [comment]
發生了什麼問題？
> 事实上，新版的git中的bash似乎改名叫做git-bash.exe了。于是build.bat中从bash开始后面的命令都不会正确的。
這個推理不成立，因爲該處調用的 bash 腳本就是在 *nix 環境開發並遷移到 Windows 的，並不要求一定用 git-bash 執行。

**Comment by cjwdoing** [comment]
我所描述的情况并不是“推理”啦，而是我实际遇到的问题~

因为win10的linux子系统是需要额外安装的，如未安装的情况下执行bash命令，系统只会返回一个错误信息，告知用户尚未安装可用的linux子系统。

由此导致，build.bat中的bash命令既没有调用git中的bash，因为它已经改名为git-bash，也没有成功调用win10中的linux子系统，因为尚未额外安装。

**Comment by cjwdoing** [comment]
此外编译中还有boost版本导致的问题。所以，不知道作者有没有可能说明一下自己用的git\cmake\boost版本~

**Comment by cjwdoing** [comment]
哈，终于编译成功了，配套的有诸多更改，比如
build bat中的bash改成git-bash，
修订“set plum_dir=plum”的值，
拷贝“winapifamily.h”等头文件到thirdparty/include目录下，
修订安装文件制作工具的路径，
给rimewithseasel工程文件中的include项目加上thirdparty/include的内容

现在能想起来的就是这么多~

如果有人想要编译win版的，但遇到了问题，可以在这里@我哈，说不定我可以提供帮助~

**Comment by lotem** [comment]
不懂
我只需按 https://github.com/rime/weasel/blob/master/INSTALL.md 做
git for windows 腳本會自動安裝這個版本
https://github.com/rime/plum/blob/master/rime-install.bat#L281

**Comment by cjwdoing** [comment]
啊？确认一下，刚才的意思是用plum/rime-install.bat自动安装整个RIME么？

如果是这样的话， https://github.com/rime/weasel/blob/master/INSTALL.md 的说明里写的是用
cd weasel
build.bat all
这个命令来安装呢。

如果是用“cd weasel + build.bat all”命令来安装的话，我按照上述命令做的时候遇到了如题目所说的问题，经过前面回答中所说的更改以后，解决了编译方面的问题的。我的环境是win10+VS2015（以前装过VS2017，然后卸载了）+1-68版本的boost。可能这里有一些编译环境配置的问题。

如果是应该用plum/rime-install.bat来安装的话，这个操作看起来和INSTALL.md 里面写的不太一样来着，也许是我忽略了其中的一些信息？ 
:-P

**Comment by lotem** [comment]
不是的， `plum/rime-install.bat` 只用來下載安裝數據文件。
如果腳本缺少所需的工具，如 Git，他會嘗試自動安裝。
你應該是自己安裝過新版 Git，所以碰到了 `git-bash` 的問題。
可知是從哪個版本改成這樣的？腳本需要兼容他。

爲啥要做其他改動我就不清楚了。

**Comment by cjwdoing** [comment]
恩，那么我对于plum/rime-install.bat的理解是正确的。

我确实是自己安装的最新版本来着，因为您的 https://github.com/rime/weasel/blob/master/INSTALL.md 里面，“Preparation”一节明确写到Install dev tools: git, cmake。所以我就安装了这两个的最新版~

至于git是从哪个版开始叫做git-bash的，我确实也不太清楚，为了编译RIME，我还是第一次用git，之前对于git的了解不是很多:-P

**Comment by cjwdoing** [comment]
此外，后面那几个关于头文件和引用目录的更改，是因为我这边如果不做这些，会有代码提示找不到winapifamily.h而编译不通过。

然后我这边还需要把“set plum_dir=plum”改成“set plum_dir=”，否则的话，会出现bash不停的运行他自身，而不会继续执行下面的语句。根据语句来观察的话，好像确实也是这样，相关语句如下：

`
run_from_plum_dir=0

if [[ -z "${plum_dir}" ]]; then
    # am I in a working copy already?
    plum_dir="$(dirname "$0")"
    if [[ -f "${plum_dir}"/scripts/install-packages.sh ]]; then
        run_from_plum_dir=1
    else
        # make a copy of plum in a subdirectory
        plum_dir='plum'
    fi
fi

if [[ "${run_from_plum_dir}" -eq 0 ]]; then
    # run newer version of rime-install
    "${plum_dir}"/rime-install "$@"
    exit
fi
`
从这个代码观察，必须plum_dir为空时，才有可能run_from_plum_dir取为1，否则就会出现上面我说的，（由于run_from_plum_dir取为0而导致的）install.sh不断运行他自身的情况。不知道我这样的观察有何错误吗？

**Comment by lotem** [comment]
的確如此。因爲 `set` 等效於 bash 裏的 `export`。
Fixed in rime/plum

**Comment by ryysoft** [comment]
我VS编译时要prop，然后git下载又总是下载不全，中间遇到各种错误，从gitee上下载时，会转github上下载librime，就会卡的退出。

**Comment by ryysoft** [comment]
楼主：
编译到opencc时出这样的错误：
CMake Warning (dev) at CMakeLists.txt:134 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Failed
-- Performing Test COMPILER_HAS_DEPRECATED
-- Performing Test COMPILER_HAS_DEPRECATED - Success
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_C_FLAGS_RELEASE


-- Build files have been written to: D:/weasel-shw/weasel/librime/thirdparty/src/opencc/build
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
版权所有(C) Microsoft Corporation。保留所有权利。

  Checking Build System
  libopencc.vcxproj -> D:\weasel-shw\weasel\librime\thirdparty\src\opencc\build\src\Release\opencc.lib
  opencc_dict.vcxproj -> D:\weasel-shw\weasel\librime\thirdparty\src\opencc\build\src\tools\Release\opencc_dict.exe
  opencc.vcxproj -> D:\weasel-shw\weasel\librime\thirdparty\src\opencc\build\src\tools\Release\opencc.exe
  opencc_phrase_extract.vcxproj -> D:\weasel-shw\weasel\librime\thirdparty\src\opencc\build\src\tools\Release\opencc_ph
  rase_extract.exe
  Building Custom Rule D:/weasel-shw/weasel/librime/thirdparty/src/opencc/CMakeLists.txt
  -- Install configuration: "Release"
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/lib/pkgconfig/opencc.pc
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/lib/opencc.lib
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/include/opencc/BinaryDict.hpp
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/include/opencc/Common.hpp
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/include/opencc/Config.hpp
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/include/opencc/Conversion.hpp
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/include/opencc/ConversionChain.hpp
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/include/opencc/Converter.hpp
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/include/opencc/DartsDict.hpp
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/include/opencc/Dict.hpp
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/include/opencc/DictConverter.hpp
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/include/opencc/DictEntry.hpp
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/include/opencc/DictGroup.hpp
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/include/opencc/Exception.hpp
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/include/opencc/Export.hpp
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/include/opencc/Lexicon.hpp
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/include/opencc/MaxMatchSegmentation.hpp
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/include/opencc/Optional.hpp
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/include/opencc/PhraseExtract.hpp
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/include/opencc/Segmentation.hpp
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/include/opencc/Segments.hpp
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/include/opencc/SerializableDict.hpp
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/include/opencc/SimpleConverter.hpp
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/include/opencc/TextDict.hpp
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/include/opencc/UTF8StringSlice.hpp
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/include/opencc/UTF8Util.hpp
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/include/opencc/opencc.h
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/bin/opencc.exe
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/bin/opencc_dict.exe
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/bin/opencc_phrase_extract.exe
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/share/opencc/STCharacters.ocd
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/share/opencc/STPhrases.ocd
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/share/opencc/TSCharacters.ocd
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/share/opencc/TSPhrases.ocd
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/share/opencc/TWVariants.ocd
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/share/opencc/TWVariantsRevPhrases.ocd
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/share/opencc/JPVariants.ocd
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/share/opencc/HKVariants.ocd
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/share/opencc/HKVariantsPhrases.ocd
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/share/opencc/HKVariantsRevPhrases.ocd
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/share/opencc/TWPhrases.ocd
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/share/opencc/TWPhrasesRev.ocd
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/share/opencc/TWVariantsRev.ocd
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/share/opencc/HKVariantsRev.ocd
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/share/opencc/s2t.json
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/share/opencc/t2s.json
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/share/opencc/s2tw.json
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/share/opencc/s2twp.json
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/share/opencc/tw2s.json
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/share/opencc/tw2sp.json
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/share/opencc/t2tw.json
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/share/opencc/s2hk.json
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/share/opencc/hk2s.json
  -- Up-to-date: D:/weasel-shw/weasel/librime/thirdparty/share/opencc/t2hk.json
PATH=e:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\\Extensions\Microsoft\IntelliCode\CLI;e:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX86\x86;e:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\VC\VCPackages;e:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow;e:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;e:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin\Roslyn;e:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Team Tools\Performance Tools;E:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\;C:\Program Files (x86)\HTML Help Workshop;e:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools;e:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\devinit;E:\Windows Kits\10\bin\10.0.19041.0\x86;E:\Windows Kits\10\bin\x86;e:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework\v4.0.30319;e:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\;e:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\;C:\Program Files (x86)\Common Files\NetSarang;C:\Python310\Scripts\;C:\Python310\;C:\Python38\Scripts\;C:\Python38\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;e:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;c:\vueProject\nodejs\node_global;C:\ProgramData\chocolatey\bin;c:\vueProject\nodejs\node_global\node_modules\cnpm\bin;C:\vueProject\nodejs\;C:\Redis-x64-3.0.504;E:\Android_SDK\JDK16\bin;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\dotnet\;E:\Program Files (x86)\NetSarang\Xmanager 7\;E:\Program Files (x86)\NetSarang\Xshell 7\;E:\Program Files (x86)\NetSarang\Xftp 7\;D:\boost_1_74_0\lib\vc10_x64\lib;C:\Program Files (x86)\YAML_CPP;C:\Program Files (x86)\glog;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;e:\Program Files\JetBrains\IntelliJ IDEA 2020.3.2\bin;;C:\Users\Administrator\AppData\Roaming\npm;C:\Users\Administrator\.dotnet\tools;e:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;e:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;e:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\VC\Linux\bin\ConnectionManagerExe

RIME_ROOT=D:\weasel-shw\weasel\librime

BOOST_ROOT=D:\boost_1_74_0

系统找不到指定的路径。
error building weasel...
