### ISSUE TITLE
overload Keybing "Escape"

### ISSUE THREAD

**Issue by WingDust** [rime/weasel#501]
i want to have a commonly used autochange Chinese/English solution to all have vim style soft .
So i try to goto look up source code for Weasel, Even if i don't good at C++.
I find in KeyEvent.cpp have `case VK_ESCAPE: return ibus:Escape;`in 100 line .
I want to change that to when press Escape if Weasel in Chinese we will change Weasel to English.And Weasel in English we keep it to English .
Sencond , When we are typing Chinese  ,Escape will be catch by System cancel input . it should be in Chinese.

But i don't how to use Weasel inside function to prove Weasel in Chinese or English And it don't was typing 

if can solve it will be very useful

**Comment by lotem** [comment]
You want something like the deleted code in this commit
https://github.com/rime/weasel/commit/9b104278d288bbd4c09861451ce136feada565c7#diff-b30c38935dcd6f5afb58c7f71b91c744
Weasel used to support gvim in that manner. The trick was removed since gvim added support for controling IME status on its own.

**Comment by WingDust** [comment]
this code it's for gvim maybe is work 
but i look for commonly used solution
Such as spacemacs neovim spacevim vscode(it's solution don't use well )

**Comment by WingDust** [comment]
@lotem

**Comment by fxliang** [comment]
solved in 0.16.0
