### ISSUE TITLE
How to enter a raw pastebin file as a custom table

### ISSUE THREAD

**Issue by TexNat** [rime/weasel#599]
I am trying to use RIME to type japanese, and i need to add kana to the table, the link i was provided with to do this was just a pastebin file(http://pastebin.com/raw/CK0zzC4D) with what i assume are the key combinations followed by the characters to be produced. how am i intended to install this as a table?

**Comment by BavonChao** [comment]
You should add the content to your custom dict `.yaml` file, like this
```
あ	a	100
い	i	100
```

**Comment by TexNat** [comment]
i see, and where would this file be?

**Comment by lotem** [comment]
Can you read docs in Chinese?
This totorial covers the steps to implement a custom dictionary in Rime:
https://github.com/rime/home/wiki/RimeWithSchemata#%E7%A2%BC%E8%A1%A8%E8%88%87%E8%A9%9E%E5%85%B8
It's a non-trivial task. You might find it helpful using one of the available configurations from this thread
https://github.com/rime/home/issues/68#issuecomment-325898895

I'm also interested in knowing why you needed to type Japanese with Rime instead of using a Japanese IME.

**Comment by TexNat** [comment]
i'm using Rime because to my knowledge there is no japanese IME that uses a stroke-based input method instead of a phonetic one, so i'm using ZhengMa through Rime

**Comment by lotem** [comment]
> i'm using Rime because to my knowledge there is no japanese IME that uses a stroke-based input method instead of a phonetic one, so i'm using ZhengMa through Rime

OK. I see what you are trying to do. 

As a quick solution you may merge the [kana](https://github.com/gkovacs/rime-japanese/blob/master/japanese.kana.dict.yaml) table into the one for Zhengma.

Or if you do not like copying code around, import the kana table from (for example) `japanese.kana.dict.yaml` by editing the YAML header in `zhengma.dict.yaml`:
```yaml
# zhengma.dict.yaml
---
# add the following lines after the original YAML config and before ...
import_tables:
  - japanese.kana
...
```

**Comment by TexNat** [comment]
this worked perfectly. thank you so much.
